### ISSUE TITLE
Getting flow generation error after enabling test_ids

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/test_ids#5]
Hi,

I enabled the test_ids gem as so:

~~~ruby
      TestIds.repo =  'ssh://git@stash.server.com:7999/osdk/test_ids.git'
      TestIds.configure :wafer_test do |config|
        config.bins.include << 5
        config.softbins = :bbb000
        config.numbers do |bin, softbin|
          (softbin * 10) + bin 
        end
      end
~~~

and I got this error when trying to generate the flow:

~~~shell
peologin07:ppekit $ origen p jtag_flow.rb
[INFO]       11.206[0.037]   || **********************************************************************
[INFO]       22.397[0.029]   || Generating... jtag_flow.rb
undefined method `[]=' for #<Proc:0x002b58a5bdc490>
Did you mean?  []
/users/user/origen/.origen/gems/ruby/2.3.0/gems/atp-1.1.1/lib/atp/flow.rb:246:in `block (2 levels) in test'
/users/user/origen/.origen/gems/ruby/2.3.0/gems/atp-1.1.1/lib/atp/flow.rb:570:in `apply_conditions'
/users/user/origen/.origen/gems/ruby/2.3.0/gems/atp-1.1.1/lib/atp/flow.rb:241:in `block in test'
/users/user/origen/.origen/gems/ruby/2.3.0/gems/atp-1.1.1/lib/atp/flow.rb:660:in `extract_meta!'
/users/user/origen/.origen/gems/ruby/2.3.0/gems/atp-1.1.1/lib/atp/flow.rb:240:in `test'
/users/user/origen/.origen/gems/ruby/2.3.0/gems/atp-1.1.1/lib/atp/flow_api.rb:20:in `block (2 levels) in <module:FlowAPI>'
/users/user/origen/.origen/gems/ruby/2.3.0/gems/test_ids-0.8.0/lib/test_ids/origen_testers/flow.rb:11:in `test'
/users/user/origen/.origen/gems/ruby/2.3.0/bundler/gems/origen_testers-0392fe1a8dd0/lib/origen_testers/interface.rb:46:in `test'
/users/user/origen/mygem/lib/mygem/interface.rb:311:in `instantiate_test'
COMPLETE CALL STACK
-------------------
~~~

I checked the repo and it did populate the first test:

~~~json
{
  "format_revision": 1,
  "assigned": {
    "bin": {
      "jtag_idcode": {
        "number": 5,
        "size": 1
      }
    },
    "softbin": {
      "jtag_idcode": {
        "number": 5000,
        "size": 1
      }
    },
    "number": {
      "jtag_idcode": {
        "number": 50005,
        "size": 1
      }
    }
  },
  "manually_assigned": {
    "bin": {
    },
    "softbin": {
    },
    "number": {
    }
  },
  "pointers": {
    "bin": 5,
    "softbin": null,
    "number": null
  },
  "references": {
    "bin": {
      "5": 1525266758.0171158
    },
    "softbin": {
      "5000": 1525266758.0171158
    },
    "number": {
      "50005": 1525266758.0171158
    }
  }
}
~~~

I know it is because our test interface assigns a proc as the on_fail option so alarm checks are added automatically. because when I removed the Proc option, the test was added to the flow correctly.  Here is the atp code that is causing the issue:

~~~ruby
    def test(instance, options = {})
      extract_meta!(options) do
        apply_conditions(options) do
          # Allows any continue, bin, or soft bin argument passed in at the options top-level to be assumed
          # to be the action to take if the test fails
          if b = options.delete(:bin)
            options[:on_fail] ||= {}
            options[:on_fail][:bin] = b
          end
          if b = options.delete(:bin_description)
            options[:on_fail] ||= {}
            options[:on_fail][:bin_description] = b
          end
          if b = options.delete(:softbin) || b = options.delete(:sbin) || b = options.delete(:soft_bin)
            options[:on_fail] ||= {}
            options[:on_fail][:softbin] = b
          end
          if b = options.delete(:softbin_description) || options.delete(:sbin_description) || options.delete(:soft_bin_description)
            options[:on_fail] ||= {}
            options[:on_fail][:softbin_description] = b
          end
~~~

Seems like we need a way to store the binning information outside of making a 2-D hash out of options.  Perhaps we could pass binning/other actions as its own hash as so:

~~~ruby
    def test(instance, options = {})
      options[:actions] = {}.tap do |bin_hash|
        bin_hash[:on_fail] = {}
        bin_hash[:on_pass] = {}
      end
      extract_meta!(options) do
        apply_conditions(options) do
          # Allows any continue, bin, or soft bin argument passed in at the options top-level to be assumed
          # to be the action to take if the test fails
          if b = options.delete(:bin)
            options[:on_fail] ||= {}
            options[:actions][:on_fail][:bin] = b
          end
~~~

Thoughts?

thx

**Comment by ginty** [comment]
Can you post a snippet of the test flow code with the Proc?

**Comment by info-rchitect** [comment]
@ginty it is added in the interface.  Here is the atp:

~~~ruby
        s(:on_fail,
          s(:if_flag, "$Alarm",
            s(:render, "multi_bin;")))),
~~~

**Comment by info-rchitect** [comment]
@ginty i can see that the `on_fail` and `on_pass` methods check for a Proc but the method that calls those methods does not.

**Comment by ginty** [comment]
Well, you're ahead of me then, please feel free to fix!

**Comment by info-rchitect** [comment]
@ginty need some help with best methods for ATP.  If I have some fail flow children that cover the binning as so:

~~~ruby
on_fail_node = n(:on_fail, children)
~~~

What is the best way to add the proc on_fail children? The code below doesn't work but I am thinking the append method seems reasonable in some form.

~~~ruby
      if options[:on_fail].is_a?(Proc)
        node = n0(:on_fail)
        on_fail_node.append << append_to(node) { options[:on_fail].call }
      end
~~~

**Comment by ginty** [comment]
OK, so you have something like this:

~~~ruby
test :blah, on_fail: -> {
  if_flag "TestFlag" do
    bin 1
  end
}
~~~

And the problem is that ATP expects `:on_fail` to be a hash. So it's not really a test_ids problem, it is only adding the :bin attribute into the equation.
I think if we made a test case like this it should fail in the same way without test_ids being involved at all:

~~~ruby
test :blah, on_fail: -> {
  if_flag "TestFlag" do
    bin 1
  end
}, bin: 10
~~~

The underlying problem is that as far as ATP is concerned, this:

~~~ruby
test :blah, bin: 10
~~~

is a shorthand for this:

~~~ruby
test :blah, on_fail: { bin: 10 }
~~~

The two are really irreconcilable, on one hand we are saying that we want it to run a custom Proc if it fails, while on the other we are saying we want to set a bin if it fails.

Probably first is to decide what it should do in this situation:

* Leave it to be resolved at application level and give a better error message
* Throw away the bin
* Apply the bin after the Proc
* Pass the bin into the Proc for it to deal with

Thoughts?

**Comment by info-rchitect** [comment]
@ginty I was able to get this to work by modifying the ATP gem as so.

1. Separate out the on_fail and on_pass 'actions' so both a Proc and a Hash can be used.

~~~ruby
   def test(instance, options = {})
      options[:actions] = {}.tap do |bin_hash|
        bin_hash[:on_fail] = {}
        bin_hash[:on_pass] = {}
      end
      options[:on_fail] ||= {}
      extract_meta!(options) do
        apply_conditions(options) do
          # Allows any continue, bin, or soft bin argument passed in at the options top-level to be assumed
          # to be the action to take if the test fails
          if b = options.delete(:bin)
            options[:actions][:bin] = b
          end
          if b = options.delete(:bin_description)
            options[:actions][:bin_description] = b
          end
          if b = options.delete(:softbin) || b = options.delete(:sbin) || b = options.delete(:soft_bin)
            options[:actions][:on_fail][:softbin] = b
          end
          if b = options.delete(:softbin_description) || options.delete(:sbin_description) || options.delete(:soft_bin_description)
            options[:actions][:on_fail][:softbin_description] = b
          end
          if options.delete(:continue)
            options[:actions][:on_fail][:continue] = true
          end
          if options.key?(:delayed)
            options[:actions][:on_fail][:delayed] = options.delete(:delayed)
          end
          if f = options.delete(:flag_pass)
            options[:actions][:on_pass][:set_flag] = f
          end
          if f = options.delete(:flag_fail)
            options[:actions][:on_fail][:set_flag] = f
          end
          #  ...
          children << on_fail(options) if options[:on_fail].is_a?(Proc) || !options[:actions][:on_fail].empty?
          children << on_pass(options) if options[:on_pass].is_a?(Proc) || !options[:actions][:on_pass].empty?
~~~

2. Updated the on_fail and on_pass methods

~~~ruby
    def on_fail(options = {})
      children = []
      if options[:on_fail].is_a?(Proc)
        node = n0(:on_fail)
        children = append_to(node) { options[:on_fail].call }.children.dup
      end
      on_fail_actions = options[:actions][:on_fail]
      if on_fail_actions[:bin] || on_fail_actions[:softbin]
        fail_opts = { bin: on_fail_actions[:bin], softbin: on_fail_actions[:softbin] }
        fail_opts[:bin_description] = on_fail_actions[:bin_description] if on_fail_actions[:bin_description]
        fail_opts[:softbin_description] = on_fail_actions[:softbin_description] if on_fail_actions[:softbin_description]
        children << set_result(:fail, fail_opts)
      end
      if on_fail_actions[:set_run_flag] || on_fail_actions[:set_flag]
        children << set_flag_node(on_fail_actions[:set_run_flag] || on_fail_actions[:set_flag])
      end
      children << n0(:continue) if on_fail_actions[:continue]
      children << n1(:delayed, !!on_fail_actions[:delayed]) if on_fail_actions.key?(:delayed)
      children << n1(:render, on_fail_actions[:render]) if on_fail_actions[:render]
      n(:on_fail, children)
    end
~~~

This results in the following ATP:

~~~sruby
  s(:test,
    s(:object, <TestSuite: jtag_idcode>),
    s(:name, "jtag_idcode"),
    s(:number, 50005),
    s(:id, "jtag_idcode"),
    s(:on_fail,
      s(:if_flag, "$Alarm",
        s(:render, "multi_bin;")),
      s(:set_result, "fail",
        s(:softbin, 5000)))),
~~~

Will this work for you?

thx

**Comment by ginty** [comment]
OK, so we apply the bin after the Proc, I'm fine with that if you are.

Its hard to see what has changed here, but in principle it seems good to me, will review properly in the PR.

Thanks!

**Comment by info-rchitect** [comment]
@ginty yes i think it is reasonable that the user should know their flow well enough such that they wouldn't put something in the fail flow, as a Proc, that would impact their binning data integrity.

**One Last question:**

Can we make generating a bin in the ATE specific flow file optional?  We would like to use the TestId config to help standardize our binning but want to use an off-line binning rules engine.  Having the binning information in the model is all we need. 

thx

**Comment by ginty** [comment]
Not sure exactly what you mean by that, can you elaborate?

**Comment by info-rchitect** [comment]
@ginty I want the JSON file created in Git and I want my test interface to know the hardbin and softbin assigned to every test but I don't want it to actually insert the bin in the ATE flow file.  I will use my test interface model to write out a 3rd party [Drools file](https://www.drools.org/) that will handle the binning offline versus using the tester to do it.

**Comment by ginty** [comment]
I see.

Yes we can definitely support that. The inhibiting from actual writing you can probably accomplish easily enough by adding an additional config option that will make it branch around this code which is where the assigned/retrieved number is injected into the options hash that is passed to the final ATE generator - https://github.com/Origen-SDK/test_ids/blob/master/lib/test_ids/allocator.rb#L123

Right now TestIds only really provides the allocate method to retrieve info from the database:

~~~ruby
TestIds.allocate(my_test, options)   # => { bin: 5, bin_size: 1, softbin: 1250, softbin_size: 1 number: 10250010, number_size: 1 }
~~~

But in due course I envisage a much richer Ruby API evolving to extract information from the store/database, probably you can start to define that based on your needs here to create this 3rd party file format.
